In [1]:
import pandas as pd
import numpy as np

## Reading Dataset

In [3]:
df = pd.read_csv("/content/cancer_dataset.csv")

In [13]:
df.shape

(569, 33)

In [4]:
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

## Seperating dependent and Independent variable

In [5]:
X = df.iloc[:,2:]
y = df.iloc[:,1]

In [6]:
# Checking our X and y
print(X.head())
print()
print(y.head())

   radius_mean  texture_mean  ...  fractal_dimension_worst  Unnamed: 32
0        17.99         10.38  ...                  0.11890          NaN
1        20.57         17.77  ...                  0.08902          NaN
2        19.69         21.25  ...                  0.08758          NaN
3        11.42         20.38  ...                  0.17300          NaN
4        20.29         14.34  ...                  0.07678          NaN

[5 rows x 31 columns]

0    M
1    M
2    M
3    M
4    M
Name: diagnosis, dtype: object


In [7]:
# droping all NaN values
X = X.dropna(axis = 1)

In [8]:
X.head()

radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [12]:
y.value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

# Hold OutValidation approach - Train and Test Split

In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.30, random_state = 0)
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
result = model.score(X_test, y_test)

In [15]:
result

0.9239766081871345

# K Fold Cross Validation

In [16]:
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
# we spliting our dataset into 10 sets
kfold_validataion = KFold(10)

In [17]:
import numpy as np
from sklearn.model_selection import cross_val_score
result = cross_val_score(model,X,y,cv=kfold_validataion)
print(result)

[0.9122807  0.9122807  0.89473684 0.94736842 0.89473684 0.98245614
 0.9122807  0.94736842 0.92982456 0.89285714]


In [18]:
# final result is the average of every individual results
print(np.mean(result))

0.9226190476190477


# Stratified K-fold Cross Validataion

Generally use when dataset having classification problem or having imbalance dataset







In [20]:
from sklearn.model_selection import StratifiedKFold
skfold = StratifiedKFold(n_splits=5)
result = cross_val_score(model,X,y,cv=skfold)
print(result)

[0.9122807  0.92105263 0.9122807  0.95614035 0.88495575]


In [21]:
print(np.mean(result))

0.9173420276354604


# Leave one out cross validation


In [22]:
# solwest of all
from sklearn.model_selection import LeaveOneOut
leave_validation = LeaveOneOut()  
result = cross_val_score(model, X,y, cv = leave_validation) 

In [23]:
result

array([1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [24]:
print(np.mean(result))

0.9226713532513181


# Repeated Random train test Split 

hybrid of train and test split and KFlod Cross Validation


In [25]:
from sklearn.model_selection import ShuffleSplit
ssplit =  ShuffleSplit(n_splits = 10, test_size = 0.30)
result = cross_val_score(model, X,y, cv = ssplit) 
result

array([0.9122807 , 0.92982456, 0.94736842, 0.91812865, 0.88888889,
       0.94152047, 0.92982456, 0.9005848 , 0.95906433, 0.93567251])

In [26]:
print(np.mean(result))

0.9263157894736842
